GET http://localhost:3001/users
Content-Type: application/json

###

GET http://localhost:3001/users/find?name=ali
Content-Type: application/json

###

GET http://localhost:3001/users/typefind?type=nor
Content-Type: application/json

###

POST http://localhost:3001/user/add
Content-Type: application/json

{
    "name": "jorge",
    "email": "bla@sOnic.com",
    "type": "NORMAL",
    "age": 14
}